### ISSUE TITLE
Announcement: Moving repo to UDST

### ISSUE THREAD

**Issue by smmaurer** [UDST/urbansim_templates#3]
Hi, I'm about to move ModelManager to UDST. 

Links should forward automatically, but to be safe you might want to update the git remote if you have a local copy of the repository:

```sh
git remote -v  # list remotes
git remote set-url origin https://github.com/udst/modelmanager.git
git remote -v
```

@mxndrwgrdnr @waddell @arezoo-bz @janowicz

**Comment by smmaurer** [comment]
Paul had suggested renaming this repository `urbansim_templates`, which I think is a good idea. It reflects the functionality more clearly, and sets us up to fold this directly into UrbanSim later on as `urbansim.templates`. 

So I'm going to rename it. You'll have to change your git remotes again, and re-run `python setup.py develop`. Apologies!

The new usage will be:

```py
from urbansim_templates import modelmanager as mm
from urbansim_templates.models import RegressionStep, BinaryLogitStep, MultinomialLogitStep
```

Within this repo, the module that interfaces between Orca and the templates will still be called `modelmanager` -- this is the piece that handles saving, loading, and registering of steps.

**Comment by mxndrwgrdnr** [comment]
Haha, I just spent the last 20 minutes trying to find the modelmanager repo before finding this message. Thanks Sam!
