### ISSUE TITLE
Relative Path

### ISSUE THREAD

**Issue by Gitiauxx** [UDST/urbansim_templates#40]
In the regression module, the line from.shared import TemplateStep generates the following error when run from a notebook: "ImportError: cannot import name 'TemplateStep'"

Probably relates to [issue 29](https://github.com/UDST/urbansim_templates/issues/29)

More generally, there seems to be some circular dependency with modulemanager calling regression with itself import modulemanager. It could work, but seems likely to generate bugs.

**Comment by Gitiauxx** [comment]
I did some further investigation:

On a Windows machine, 
`from urbansim_templates import modelmanager` generates an error message when trying to load regression and then shared

On a Ubuntu machine,
There is no error.

I tried other imports (e.g. `from urbansim_templates.models import regression`) and obtain the same pattern: error on Windows machine and no error on Ubuntu machine.

**Comment by smmaurer** [comment]
Interesting. So it looks like there are consistent problems with the import statements in Windows, but we're not sure yet whether it's because of the circularity or something else with the syntax. Am i understanding it right?

Trying out [ChoiceModels](https://github.com/UDST/choicemodels) in Windows might help diagnose this -- it looks like it uses similar relative import syntax without any circularity.

Copying over some of our Slack discussion: 

1. We haven't run into problems with this on MacOS or Ubuntu, but I don't think anyone's been using the code in Windows yet.

2. You're right that the circularity seems like a bad pattern, even if it turns out not to be causing this problem.. Some potential solutions include: 
    - moving the `register()` method out of the template classes, and having the user invoke `modelmanager` for this instead, or 
    - figuring out how to avoid importing the template definitions into `modelmanager` -- see comments at [modelmanager.py#L105-L114](https://github.com/UDST/urbansim_templates/blob/master/urbansim_templates/modelmanager.py#L105-L114).

Either or both of these might be a good idea. I think i'd lean toward the latter if it's feasible; i will take a look tomorrow.

**Comment by Gitiauxx** [comment]
I think that it is a good summary.

It does not seem that choicemodel gives any trouble, even on Windows.

 Let me see if I can avoid importing the steps in the model manager. That seems easier than moving register to model manager. Then, we can test whether the relative path are still a problem on any type of machine.

**Comment by Gitiauxx** [comment]
Unfortunately, I forgot that globals() does not seem to be shared across modules.... 

Therefore, I created a shared module, settings, that keeps track of the steps imported. When starting a notebook, we could load the necessary steps. They will be recorded by settings. Modelmanager will then load settings and go from there without importing each step. 

I committed those changes in my branch (see test_structure). I still do not like the two lines

`pipe_steps['OLSRegressionStep'] = OLSRegressionStep()
pipe_steps['RandomForestRegressionStep'] = RandomForestRegressionStep()`

I will think whether we can automate that part. However, this code seems to work on every plattform I tested it (2 Windows and an Ubuntu).

**Comment by Gitiauxx** [comment]
I agree.... One idea I had is to follow the sklearn.pipeline approach, where modelmanager will take as inputs objects (with run, from_dict and to_dict attribute, that seems the bare minimum) and register the object in orca, save its config in yaml/pickle. There are 2 configurations:

Case 1: the step is not yet in a yaml file. Then, the user in her notebook or somewhere else will write:
'from .model import Step
modelmanager.do_something(Step)'
 where do_something will be adding a step, getting a step... The advantage here is that we do not need to import Step in modelmanager since it is an input.

Case 2: the step is already constructed in a yaml file. Then, the user in her notebook or somewhere else will write:
'from .model import Step 
modulemanager.initialize(Step, yaml=True)'


Case2 is the difficult one because we cannot directly share the imported modules with modelmanager. Using the Step object as an input helps a little, but if we have many steps, that may be ugly: 

`modulemanager.initialize(Step1,`` yaml=True)
modulemanager.initialize(Step1, yaml=True)  .....'

But a wrapper, like the current modelmanager.initialize() would not work either because it will not see that Step1 and Step2 have been imported from the notebook...

**Comment by smmaurer** [comment]
This seems promising!

I also just made a `remove-circularity` branch ([view diff](https://github.com/UDST/urbansim_templates/compare/remove-circularity)) that implements moving the `register()` method out of the templates and into `modelmanager`. 

So the new usage is:
```py
from urbansim_templates.models import <ModelName>
from urbansim_templates import modelmanager

modelmanager.initialize()
m = <configured ModelName>
modelmanage.register(m)
```

Maybe this actually makes more sense than having `register()` as a method of the object. Anyway, it removes the need for the template definitions to have access to `modelmanager`, eliminating the circularity.

@Gitiauxx, could you try checking out this branch and seeing if the imports work on your machine?

**Comment by Gitiauxx** [comment]
Yes, because it will reduce the requirements on the steps, so less work for
the user.

Also, I think I figure out a way to solve case 2 elegantly. What about we
pickle the objects everyone we save a step. Then, the next time we need
that step, modelmanager will unpickle the file. It should not need to
import the step since the object is already built.

I will try this and see that works.

Xavier

**Comment by Gitiauxx** [comment]
And I will work from the new branch.

**Comment by Gitiauxx** [comment]
Without the circularity, the bugs seems to be gone on all the machine I have tested urbansim_templates.

**Comment by smmaurer** [comment]
Excellent! Very good news.
