### ISSUE TITLE
Small MNL `run()` method cannot read model expression params from yaml config

### ISSUE THREAD

**Issue by mxndrwgrdnr** [UDST/urbansim_templates#71]
Since PyLogit models expressions are stored as OrderedDict types, and OrdereredDicts can't be stored as yaml, the small MNL `to_dict()` method refactors the model expression into model expression keys and model expression values, seen [here](https://github.com/UDST/urbansim_templates/blob/master/urbansim_templates/models/small_multinomial_logit.py#L183-L188), and sets the model expression itself to None. It would seem, however, that `TemplateStep._get_data()` method in shared.py is unaware of this fact, because it still looks for a model expression, rather than model expression keys and values, which is the method currently called by the small MNL's `run()` command. It looks like the `_get_data()` method itself is deprecated, and should eventually be replaced by `_get_df()`, but unfortunately the `_get_df()` method doesn't yet handle model expressions either. So, this definitely seems like a bug at least for the moment, and since `_get_data()` is deprecated it probably makes more sense to implement the fix within `_get_df()`. I also know that you @smmaurer  are working on a fix for filtering relevant columns from model expressions right now, which is exactly what would need to be implemented in `_get_df()` to bring it up to speed with what `_get_data()` was previously doing, and I don't want to duplicate any work. Any ideas on how to proceed?

**Comment by smmaurer** [comment]
After a bunch of discussion and digging, this turns out to be a simple bug.

In the Small MNL `to_dict()` method, the `model_expression` is inadvertently deleted from the copy of the model step in memory: [small_multinomial_logit.py#L179](https://github.com/UDST/urbansim_templates/blob/master/urbansim_templates/models/small_multinomial_logit.py#L179).

This is fixed in PR #73.
